export const bingoMock: string[] = [
  'Vilket jävla hugg',
  'Snoken ropar "vilket jävla hugg"',
  'Danne härmar snoken.',
  'Trumman går på grund',
  'Henke fiskar spinnerbait',
  'Holgersson har en gameplan.',
  'Claes börjar sjunga.',
  'Claes smörjer in sin i gäddslemm',
  'Claes Claesson gör roliga röster',
  'En missad highfive',
  'Någon gubbstönar och lyfter upp en gädda',
  '"Det är en uppgreeejd"',
  '"Gäddor har inga händer"',
  '"Kolla virveln"',
  'Snoken tappar en "metersfisk"',
  'Henke pratar om kaffe',
  'Det är tjockt med betesfisk',
  'Fränstam föreläser för Evelina',
  '"Det är iallafall en gädda"',
  '"En slips"',
  'Mathias Holgersson är uppgiven',
  'Gäddlunken',
  '"Håven, håven, håven"',
  'Team SvartZonker ligger sist',
  '"En cykelpump"',
  '"De e inte sant"',
  'Fränstam badar',
  'Nicklas Jonsson har "Knäckt koden"',
  '"Det känns som att det kan smälla när som helst"',
  'Henke får påminna Nicklas om att inte svära'
];
